// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: raftcomm/raftcomm.proto

package raftcomm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_raftcomm_raftcomm_proto protoreflect.FileDescriptor

const file_raftcomm_raftcomm_proto_rawDesc = "" +
	"\n" +
	"\x17raftcomm/raftcomm.proto\x12\braftcomm\x1a\x1craftcomm/appendentries.proto\x1a\x1araftcomm/requestvote.proto\x1a\x1eraftcomm/installsnapshot.proto\x1a\x1araftcomm/healthcheck.proto2\x89\x02\n" +
	"\x11RaftCommunication\x12P\n" +
	"\rAppendEntries\x12\x1e.raftcomm.AppendEntriesRequest\x1a\x1f.raftcomm.AppendEntriesResponse\x12J\n" +
	"\vRequestVote\x12\x1c.raftcomm.RequestVoteRequest\x1a\x1d.raftcomm.RequestVoteResponse\x12V\n" +
	"\x0fInstallSnapShot\x12 .raftcomm.InstallSnapshotRequest\x1a!.raftcomm.InstallSnapshotResponse2S\n" +
	"\vHealthCheck\x12D\n" +
	"\x05Check\x12\x1c.raftcomm.HealthCheckRequest\x1a\x1d.raftcomm.HealthCheckResponseB@Z>github.com/jialuohu/curlyraft/internal/proto/raftcomm;raftcommb\x06proto3"

var file_raftcomm_raftcomm_proto_goTypes = []any{
	(*AppendEntriesRequest)(nil),    // 0: raftcomm.AppendEntriesRequest
	(*RequestVoteRequest)(nil),      // 1: raftcomm.RequestVoteRequest
	(*InstallSnapshotRequest)(nil),  // 2: raftcomm.InstallSnapshotRequest
	(*HealthCheckRequest)(nil),      // 3: raftcomm.HealthCheckRequest
	(*AppendEntriesResponse)(nil),   // 4: raftcomm.AppendEntriesResponse
	(*RequestVoteResponse)(nil),     // 5: raftcomm.RequestVoteResponse
	(*InstallSnapshotResponse)(nil), // 6: raftcomm.InstallSnapshotResponse
	(*HealthCheckResponse)(nil),     // 7: raftcomm.HealthCheckResponse
}
var file_raftcomm_raftcomm_proto_depIdxs = []int32{
	0, // 0: raftcomm.RaftCommunication.AppendEntries:input_type -> raftcomm.AppendEntriesRequest
	1, // 1: raftcomm.RaftCommunication.RequestVote:input_type -> raftcomm.RequestVoteRequest
	2, // 2: raftcomm.RaftCommunication.InstallSnapShot:input_type -> raftcomm.InstallSnapshotRequest
	3, // 3: raftcomm.HealthCheck.Check:input_type -> raftcomm.HealthCheckRequest
	4, // 4: raftcomm.RaftCommunication.AppendEntries:output_type -> raftcomm.AppendEntriesResponse
	5, // 5: raftcomm.RaftCommunication.RequestVote:output_type -> raftcomm.RequestVoteResponse
	6, // 6: raftcomm.RaftCommunication.InstallSnapShot:output_type -> raftcomm.InstallSnapshotResponse
	7, // 7: raftcomm.HealthCheck.Check:output_type -> raftcomm.HealthCheckResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raftcomm_raftcomm_proto_init() }
func file_raftcomm_raftcomm_proto_init() {
	if File_raftcomm_raftcomm_proto != nil {
		return
	}
	file_raftcomm_appendentries_proto_init()
	file_raftcomm_requestvote_proto_init()
	file_raftcomm_installsnapshot_proto_init()
	file_raftcomm_healthcheck_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftcomm_raftcomm_proto_rawDesc), len(file_raftcomm_raftcomm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_raftcomm_raftcomm_proto_goTypes,
		DependencyIndexes: file_raftcomm_raftcomm_proto_depIdxs,
	}.Build()
	File_raftcomm_raftcomm_proto = out.File
	file_raftcomm_raftcomm_proto_goTypes = nil
	file_raftcomm_raftcomm_proto_depIdxs = nil
}
