// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: raftcomm.proto

package raftcomm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_raftcomm_proto protoreflect.FileDescriptor

const file_raftcomm_proto_rawDesc = "" +
	"\n" +
	"\x0eraftcomm.proto\x12\braftcomm\x1a\x13appendentries.proto\x1a\x11requestvote.proto2\xb1\x01\n" +
	"\x11RaftCommunication\x12P\n" +
	"\rAppendEntries\x12\x1e.raftcomm.AppendEntriesRequest\x1a\x1f.raftcomm.AppendEntriesResponse\x12J\n" +
	"\vRequestVote\x12\x1c.raftcomm.RequestVoteRequest\x1a\x1d.raftcomm.RequestVoteResponseB\x19Z\x17internal/proto;raftcommb\x06proto3"

var file_raftcomm_proto_goTypes = []any{
	(*AppendEntriesRequest)(nil),  // 0: raftcomm.AppendEntriesRequest
	(*RequestVoteRequest)(nil),    // 1: raftcomm.RequestVoteRequest
	(*AppendEntriesResponse)(nil), // 2: raftcomm.AppendEntriesResponse
	(*RequestVoteResponse)(nil),   // 3: raftcomm.RequestVoteResponse
}
var file_raftcomm_proto_depIdxs = []int32{
	0, // 0: raftcomm.RaftCommunication.AppendEntries:input_type -> raftcomm.AppendEntriesRequest
	1, // 1: raftcomm.RaftCommunication.RequestVote:input_type -> raftcomm.RequestVoteRequest
	2, // 2: raftcomm.RaftCommunication.AppendEntries:output_type -> raftcomm.AppendEntriesResponse
	3, // 3: raftcomm.RaftCommunication.RequestVote:output_type -> raftcomm.RequestVoteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raftcomm_proto_init() }
func file_raftcomm_proto_init() {
	if File_raftcomm_proto != nil {
		return
	}
	file_appendentries_proto_init()
	file_requestvote_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftcomm_proto_rawDesc), len(file_raftcomm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raftcomm_proto_goTypes,
		DependencyIndexes: file_raftcomm_proto_depIdxs,
	}.Build()
	File_raftcomm_proto = out.File
	file_raftcomm_proto_goTypes = nil
	file_raftcomm_proto_depIdxs = nil
}
