// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gateway_gateway_proto protoreflect.FileDescriptor

const file_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/gateway.proto\x12\agateway\x1a\x1bgateway/appendcommand.proto\x1a\x19gateway/healthcheck.proto2]\n" +
	"\vRaftGateway\x12N\n" +
	"\rAppendCommand\x12\x1d.gateway.AppendCommandRequest\x1a\x1e.gateway.AppendCommandResponse2Q\n" +
	"\vHealthCheck\x12B\n" +
	"\x05Check\x12\x1b.gateway.HealthCheckRequest\x1a\x1c.gateway.HealthCheckResponseB>Z<github.com/jialuohu/curlyraft/internal/proto/gateway;gatewayb\x06proto3"

var file_gateway_gateway_proto_goTypes = []any{
	(*AppendCommandRequest)(nil),  // 0: gateway.AppendCommandRequest
	(*HealthCheckRequest)(nil),    // 1: gateway.HealthCheckRequest
	(*AppendCommandResponse)(nil), // 2: gateway.AppendCommandResponse
	(*HealthCheckResponse)(nil),   // 3: gateway.HealthCheckResponse
}
var file_gateway_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.RaftGateway.AppendCommand:input_type -> gateway.AppendCommandRequest
	1, // 1: gateway.HealthCheck.Check:input_type -> gateway.HealthCheckRequest
	2, // 2: gateway.RaftGateway.AppendCommand:output_type -> gateway.AppendCommandResponse
	3, // 3: gateway.HealthCheck.Check:output_type -> gateway.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gateway_proto_init() }
func file_gateway_gateway_proto_init() {
	if File_gateway_gateway_proto != nil {
		return
	}
	file_gateway_appendcommand_proto_init()
	file_gateway_healthcheck_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_proto_depIdxs,
	}.Build()
	File_gateway_gateway_proto = out.File
	file_gateway_gateway_proto_goTypes = nil
	file_gateway_gateway_proto_depIdxs = nil
}
